name: Build Gradle project

on:
  push:
    branches:
      - main

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    env:
      ALIAS: appsec
    #  KEYSTORE: keystore
    #  PASSWORD: ${{ secrets.PASSWORD }}
    #  CERTIFICATE: ppdt-certificate

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'gradle'

      # - name: Create Key Store
      #  run: sh create_keystore.sh

      - name: Run Gradle Testing
        run: sh gradlew build

      # - name: Upload coverage reports to Codecov
      #  uses: codecov/codecov-action@v3
      #  with:
      #    token: ${{ secrets.CODECOV_TOKEN }}
